name: Update Deray Configs

on:
  schedule:
    - cron: '0 * * * *'     # Запуск каждый час
  workflow_dispatch:        # Возможность ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run collector
        run: python collector.py

      - name: Commit and push if changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # Добавляем только новый итоговый файл
          git add deray.txt
          if git diff --quiet --cached; then
            echo "No changes to commit"
          else
            git commit -m "Update deray.txt - $(date +'%Y-%m-%d %H:%M')"
            git push
      
          fi
